name = "ironlog-worker"
main = "src/index.ts"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "ironlog-db"
database_id = "4c12098f-d690-45a8-874d-1e454f47b657"

[env.production]
d1_databases = [
  { binding = "DB", database_name = "ironlog-db", database_id = "4c12098f-d690-45a8-874d-1e454f47b657" },
]
